[View in Colaboratory](https://colab.research.google.com/github/Sumindar/tensorflowtutorials/blob/master/basicsoftensorflow.ipynb)

tensorflow basics

In [0]:
import tensorflow as tf


In [0]:
zero=tf.Variable(0)

In [0]:
one=tf.constant(1)

In [0]:
new_value=tf.add(zero,one)

In [0]:
update=tf.assign(zero,new_value)

In [0]:
init_op=tf.global_variables_initializer()

In [0]:
sess=tf.Session()

In [0]:
sess.run(init_op)

In [9]:
print(sess.run(zero))

0


In [11]:
for _ in range(5):
  sess.run(update)
  print(sess.run(zero))

1
2
3
4
5


### String Operations

In [0]:
hello=tf.constant("hello")

In [0]:
world=tf.constant("world")

In [0]:
helloworld=tf.add(hello,world)

In [19]:
print(sess.run(helloworld))

b'helloworld'


# **Placeholder**

In [0]:
a=tf.placeholder(tf.float32)

In [0]:
b=a*2

In [23]:
#feeding a placeholder with scalar
#result=sess.run(b,feed_dict={a:3}) 
result=sess.run(b,{a:3})
#both are correct codes to present the same concept
print(result)

6.0


In [24]:
#feeding a placeholder with vector of rank 1
result=sess.run(b,feed_dict={a:[3,4,5]})
print(result)


[ 6.  8. 10.]


In [29]:
#feeding a placeholder with multidimensional vector
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}
result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [28]:
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]]}
result=sess.run(b,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]
  [26. 28. 30.]
  [32. 34. 36.]]]


In [0]:
sess.close()

# Common syntax to create session

In [31]:
with tf.Session() as sess:
  result=sess.run(hello+world)
  print(result)
  

b'helloworld'


# Demo to explain tf program structure

In [0]:
import tensorflow as tf

In [0]:
graph=tf.get_default_graph()

In [34]:
graph.get_operations()

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>]

In [0]:
a=tf.constant(10,name='a')

In [37]:
operations=graph.get_operations()
operations

[<tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Add' type=Add>,
 <tf.Operation 'Assign' type=Assign>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add_2' type=Add>,
 <tf.Operation 'a' type=Const>]

In [0]:
tensor_1=tf.constant(1)

In [0]:
tensor_2=tf.constant(2)

In [40]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [41]:
tensor_1+tensor_2

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [42]:
sess

In [0]:
sess.close()